name: Deploy Jaspr Site

on:
  push:
    branches: [ main ]

# صلاحيات النشر المطلوبة لـ GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: Install dependencies
        run: dart pub get

      - name: Build Web
        run: jaspr build

      - name: Set GitHub Pages base path
        run: |
          repo_name="${GITHUB_REPOSITORY#*/}"
          sed -i "s#<base href=\"/\"/>#<base href=\"/${repo_name}/\"/>#" build/jaspr/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/jaspr'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4